import {
  Activity,
  AlarmClock,
  Apple,
  Bed,
  Bike,
  BookOpen,
  Brain,
  BriefcaseBusiness,
  CircleDot,
  Code2,
  Coffee,
  Cross,
  Dumbbell,
  Flame,
  Footprints,
  Gamepad2,
  GlassWater,
  GraduationCap,
  Heart,
  Home,
  Laptop,
  Leaf,
  Library,
  Lightbulb,
  type LucideIcon,
  Medal,
  Moon,
  Music,
  NotebookPen,
  Palette,
  PersonStanding,
  PhoneOff,
  Pill,
  Plane,
  Salad,
  Save,
  ShieldCheck,
  Sparkles,
  Star,
  Sun,
  Sunrise,
  Target,
  Timer,
  Trophy,
  Utensils,
  WalletCards,
  Waves,
  Zap
} from 'lucide-react'

export const commitmentIcons: Record<string, LucideIcon> = {
  activity: Activity,
  'alarm-clock': AlarmClock,
  apple: Apple,
  bed: Bed,
  bike: Bike,
  'book-open': BookOpen,
  brain: Brain,
  briefcase: BriefcaseBusiness,
  code: Code2,
  coffee: Coffee,
  cross: Cross,
  dumbbell: Dumbbell,
  flame: Flame,
  footprints: Footprints,
  game: Gamepad2,
  water: GlassWater,
  graduation: GraduationCap,
  heart: Heart,
  home: Home,
  laptop: Laptop,
  leaf: Leaf,
  library: Library,
  lightbulb: Lightbulb,
  medal: Medal,
  moon: Moon,
  music: Music,
  notebook: NotebookPen,
  palette: Palette,
  person: PersonStanding,
  'phone-off': PhoneOff,
  pill: Pill,
  plane: Plane,
  salad: Salad,
  save: Save,
  shield: ShieldCheck,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  sunrise: Sunrise,
  target: Target,
  timer: Timer,
  trophy: Trophy,
  utensils: Utensils,
  wallet: WalletCards,
  waves: Waves,
  lightning: Zap,
  sport: CircleDot
}

export const commitmentIconNames = Object.keys(commitmentIcons)
